blank_issues_enabled: false
contact_links:
  - name: 💬 Questions, ideas & general feedback
    url: https://github.com/klppl/orbitjumper-tracker/discussions
    about: For open-ended discussion, questions, and feedback that isn't a specific bug or feature request.
